apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deploy1
  labels:
    app: hasherApp
  annotations:
    fluxcd.io/tag.hasher-app: glob:1.0.*
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasherApp
  template:
    metadata:
      labels:
        app: hasherApp
    spec:
      containers:
      - name: hasher-app
        image: brahamirabah94/hasher:1.0.1
        ports:
        - conatinerPort: 80
