apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher-app
  name: hasher-service
spec:
  clusterIP: None
  ports:
  - port: 8083
    targetPort: 80
  selector:
    app: hasher-app
