apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  namespace: dockercoin
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
