---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng-app
  name: rng-deploy
  namespace: dockercoin
  annotations:
    fluxcd.io/tag.rng-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng-app
  template:
    metadata:
      labels:
        app: rng-app
    spec:
      containers:
      - name: rng-app
        image: rabah945/rng:1.0.174
        ports:
        - containerPort: 80
