---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-app
  name: worker-deploy
  annotations:
    fluxcd.io/tag.worker-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - image: rabah945/worker:1.0.169
        name: worker-app
