# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: AzureCLI@2
  displayName: checkov scan
  inputs:
    azureSubscription: 'MyConnectionAzure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        az aks get-credentials -n teoSch-aks-cluster -g rg-teoschool-rabah-001 --admin
        kubectl apply -f https://raw.githubusercontent.com/bridgecrewio/checkov/master/kubernetes/checkov-job.yaml

        wait 60
        
        kubectl logs job/checkov -n checkov > $(System.DefaultWorkingDirectory)/tests/Test-checkov-k8s.xml

        sed -i '$d' $(System.DefaultWorkingDirectory)/tests/Test-checkov-k8s.xml
        vi $(System.DefaultWorkingDirectory)/tests/Test-checkov-k8s.xml
        sed -i '$d' $(System.DefaultWorkingDirectory)/tests/Test-checkov-k8s.xml
        
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'Test-*.xml'
    searchFolder:  '$(System.DefaultWorkingDirectory)/tests'
    testRunTitle: 'test-checkov'
    publishRunAttachments: true

- task: UsePythonVersion@0
  condition: succeededOrFailed()
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r $(System.DefaultWorkingDirectory)/requirement.txt
  displayName: 'Install dependencies'
  condition: succeededOrFailed()


- script: |
    pip install pytest pytest-azurepipelines
    pytest  $(System.DefaultWorkingDirectory)/rng -rA --junitxml="Test-report-u.xml"
  displayName: 'pytest'
  condition: succeededOrFailed()

