#hasher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deploy
  namespace: dockercoin
  labels:
    app: hasher-app
  annotations:
    fluxcd.io/tag.hasher-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher-app
  template:
    metadata:
      labels:
        app: hasher-app
    spec:
      containers:
      - name: hasher-app
        image: rabah945/hasher:1.0.174
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher-app
  name: hasher-service
  namespace: dockercoin
spec:
  clusterIP: None
  ports:
  - port: 8083
    targetPort: 80
  selector:
    app: hasher-app
#redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  namespace: dockercoin
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-deploy
  namespace: dockercoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis-container
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-store
      volumes:
      - name: redis-store
        emptyDir: {}
#rng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng-app
  name: rng-deploy
  namespace: dockercoin
  annotations:
    fluxcd.io/tag.rng-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng-app
  template:
    metadata:
      labels:
        app: rng-app
    spec:
      containers:
      - name: rng-app
        image: rabah945/rng:1.0.174
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rng-service
  namespace: dockercoin
spec:
  clusterIP: None
  selector:
    app: rng-app
  ports:
  - port: 8082 
    targetPort: 80
#webui
---
apiVersion: v1 
kind: Service
metadata: 
  name: webui-service
  namespace: dockercoin
spec: 
  selector: 
    app: webui-app
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 80 
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui-app
  name: webui-deploy
  namespace: dockercoin
  annotations:
    fluxcd.io/tag.webui-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-app
  template:
    metadata:
      labels:
        app: webui-app
    spec:
      containers:
      - image: rabah945/webui:1.0.174
        name: webui-app
        ports:
        - containerPort: 80
          name: webui-port
#worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-app
  name: worker-deploy
  namespace: dockercoin
  annotations:
    fluxcd.io/tag.worker-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - image: rabah945/worker:1.0.174
        name: worker-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker-app
  name: worker-service
  namespace: dockercoin
spec:
  selector:
    app: worker-app
  clusterIP: None
